/* This file is automatically generated by Lemon from input grammar
** source file "lib/parser/syntaxis/opam_syntaxis.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 4 "lib/parser/syntaxis/opam_syntaxis.y"

#include <assert.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#include "utarray.h"
#include "uthash.h"

#include "liblogc.h"

#if INTERFACE
#ifndef YYMALLOCARGTYPE
#define YYMALLOCARGTYPE size_t
#endif
#endif

#define DEBUG_LEVEL debug_opamc_syntaxis
int  DEBUG_LEVEL;
#define TRACE_FLAG trace_opamc_syntaxis
bool TRACE_FLAG;

#line 53 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
#include "opam_syntaxis.h"
//lemp->filename "lib/parser/syntaxis/opam_syntaxis.y"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#if INTERFACE
#define AMP                             1
#define AUTHORS                         2
#define AVAILABLE                       3
#define BANG                            4
#define BUG_REPORTS                     5
#define BOOL                            6
#define BUILD                           7
#define BUILD_DOC                       8
#define BUILD_ENV                       9
#define COLON                          10
#define COMMA                          11
#define CONFLICTS                      12
#define CONFLICT_CLASS                 13
#define DEPENDS                        14
#define DEPEXTS                        15
#define DEPOPTS                        16
#define DESCRIPTION                    17
#define DEV_REPO                       18
#define DOC                            19
#define DQ                             20
#define EQ                             21
#define ERROR                          22
#define EXTRA_FILES                    23
#define EXTRA_SOURCE                   24
#define FALSE                          25
#define FEATURES                       26
#define FLAGS                          27
#define FVF_LOGOP                      28
#define HOMEPAGE                       29
#define IDENT                          30
#define IDENTCHAR                      31
#define INSTALL                        32
#define INT                            33
#define KEYWORD                        34
#define LBRACE                         35
#define LBRACKET                       36
#define LICENSE                        37
#define LOGOP                          38
#define LPAREN                         39
#define MAINTAINER                     40
#define MESSAGES                       41
#define OPAM_VERSION                   42
#define PACKAGE                        43
#define PATCHES                        44
#define PIN_DEPENDS                    45
#define PKGNAME                        46
#define POST_MESSAGES                  47
#define QMARK                          48
#define RBRACE                         49
#define RBRACKET                       50
#define REMOVE                         51
#define RELOP                          52
#define RPAREN                         53
#define RUNTEST                        54
#define SETENV                         55
#define SQ                             56
#define STRING                         57
#define STRING3                        58
#define SUBSTS                         59
#define SYNOPSIS                       60
#define TAGS                           61
#define TERM                           62
#define TERM_STRING                    63
#define TERM_VARIDENT                  64
#define TQ                             65
#define TRUE                           66
#define URL                            67
#define VARIDENT                       68
#define VERSION                        69
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 88
#define YYACTIONTYPE unsigned char
#if INTERFACE
#define ParseTOKENTYPE  union opam_token_u 
#endif
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
  struct opam_deps_s * yy26;
  struct opam_binding_s * yy33;
  UT_array * yy126;
  struct opam_package_s * yy138;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#if INTERFACE
#define ParseARG_SDECL  struct opam_parse_state_s *opam_parse_state ;
#define ParseARG_PDECL , struct opam_parse_state_s *opam_parse_state 
#define ParseARG_PARAM ,opam_parse_state 
#define ParseARG_FETCH  struct opam_parse_state_s *opam_parse_state =yypParser->opam_parse_state ;
#define ParseARG_STORE yypParser->opam_parse_state =opam_parse_state ;
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#endif
#define YYNSTATE             84
#define YYNRULE              46
#define YYNRULE_WITH_ACTION  46
#define YYNTOKEN             70
#define YY_MAX_SHIFT         83
#define YY_MIN_SHIFTREDUCE   84
#define YY_MAX_SHIFTREDUCE   129
#define YY_ERROR_ACTION      130
#define YY_ACCEPT_ACTION     131
#define YY_NO_ACTION         132
#define YY_MIN_REDUCE        133
#define YY_MAX_REDUCE        178
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (301)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   133,  134,  131,   30,   68,   20,    7,   79,  134,  153,
 /*    10 */   152,   41,   74,  134,   76,  134,  153,  152,   48,   43,
 /*    20 */    51,  153,  152,  153,  152,   22,   23,   64,   64,   47,
 /*    30 */    61,   53,   78,  134,   83,  134,   54,   11,   58,   59,
 /*    40 */    62,  153,  152,  153,  152,  141,  140,    1,   16,   67,
 /*    50 */    14,  144,  141,  140,   77,  134,  163,  141,  140,  141,
 /*    60 */   140,  139,  178,  153,  152,  144,   57,  163,  139,  178,
 /*    70 */   168,  168,    9,  139,  178,  139,  178,  141,  140,  141,
 /*    80 */   140,   10,   24,   81,   18,  168,   39,   63,   15,    8,
 /*    90 */    56,   37,  168,  139,  178,  139,  178,  177,  138,  141,
 /*   100 */   140,   55,   33,  168,  177,  138,  137,  136,   13,  177,
 /*   110 */   138,  177,  138,  137,  136,  139,  178,  154,  137,  136,
 /*   120 */   137,  136,   12,   52,  154,   65,    2,   66,   79,  177,
 /*   130 */   138,  177,  138,   74,    2,   76,   29,  165,  137,  136,
 /*   140 */   137,  136,  135,  146,  146,   42,   45,    4,  175,  135,
 /*   150 */    15,  177,  138,   78,  135,   83,  135,   40,  146,  175,
 /*   160 */   137,  136,  175,  175,   34,   82,    3,    5,   15,  161,
 /*   170 */   161,  162,  162,  142,  135,   77,  135,  161,   24,  162,
 /*   180 */   145,  161,   35,  162,  161,    8,  162,  142,   14,   31,
 /*   190 */   160,  160,  159,  159,  145,  167,  135,  147,  160,    6,
 /*   200 */   159,   72,  160,   60,  159,  160,  167,  159,   25,  158,
 /*   210 */    50,   17,  147,  151,   25,  157,  158,  150,   25,  147,
 /*   220 */   158,   49,  157,  158,  143,  166,  157,  149,  151,  148,
 /*   230 */   147,   70,  150,   44,  164,  151,  166,   73,  143,  150,
 /*   240 */   155,  174,  149,  173,  148,  164,  151,  155,   19,  149,
 /*   250 */   150,  148,  174,  172,  173,   12,  174,   12,  173,  171,
 /*   260 */   149,  170,  148,   75,  172,   26,  176,  172,  172,   36,
 /*   270 */   171,   13,  170,  171,  171,  170,  170,  176,   13,   21,
 /*   280 */    12,  176,  169,  156,   24,   12,  169,   27,   28,   46,
 /*   290 */   156,    8,   12,   38,  156,   32,   80,   69,  132,  132,
 /*   300 */    71,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */     0,    0,   70,   71,   77,   78,   74,    7,    7,    0,
 /*    10 */     0,   71,   12,   12,   14,   14,    7,    7,   79,   83,
 /*    20 */    81,   12,   12,   14,   14,   84,   84,   86,   86,   72,
 /*    30 */    87,   87,   32,   32,   34,   34,   87,    4,   87,   87,
 /*    40 */    87,   32,   32,   34,   34,    0,    0,   80,   82,   79,
 /*    50 */    35,   36,    7,    7,   54,   54,   38,   12,   12,   14,
 /*    60 */    14,    0,    0,   54,   54,   50,   33,   49,    7,    7,
 /*    70 */    35,   36,   39,   12,   12,   14,   14,   32,   32,   34,
 /*    80 */    34,   48,   39,   57,   82,   50,   75,   69,   36,   46,
 /*    90 */    57,   65,   57,   32,   32,   34,   34,    0,    0,   54,
 /*   100 */    54,   68,   50,   68,    7,    7,    0,    0,   38,   12,
 /*   110 */    12,   14,   14,    7,    7,   54,   54,   50,   12,   12,
 /*   120 */    14,   14,   52,   53,   57,   85,   38,   72,    7,   32,
 /*   130 */    32,   34,   34,   12,   38,   14,   36,   49,   32,   32,
 /*   140 */    34,   34,    0,   35,   36,   49,   72,   76,   38,    7,
 /*   150 */    36,   54,   54,   32,   12,   34,   14,   57,   50,   49,
 /*   160 */    54,   54,   52,   53,   50,   65,   35,   76,   36,   38,
 /*   170 */    39,   38,   39,   36,   32,   54,   34,   46,   39,   46,
 /*   180 */    36,   50,   50,   50,   53,   46,   53,   50,   35,   50,
 /*   190 */    38,   39,   38,   39,   50,   38,   54,   35,   46,   76,
 /*   200 */    46,   73,   50,   50,   50,   53,   49,   53,   38,   39,
 /*   210 */    57,   36,   50,   35,   38,   39,   46,   35,   38,   57,
 /*   220 */    50,   68,   46,   53,   36,   38,   50,   35,   50,   35,
 /*   230 */    68,   57,   50,   53,   38,   57,   49,   10,   50,   57,
 /*   240 */    50,   38,   50,   38,   50,   49,   68,   57,   36,   57,
 /*   250 */    68,   57,   49,   38,   49,   52,   53,   52,   53,   38,
 /*   260 */    68,   38,   68,   10,   49,   36,   38,   52,   53,   65,
 /*   270 */    49,   38,   49,   52,   53,   52,   53,   49,   38,   10,
 /*   280 */    52,   53,   49,   39,   39,   52,   53,   36,   36,   49,
 /*   290 */    46,   46,   52,   50,   50,   50,   58,   58,   88,   88,
 /*   300 */    57,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*   310 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*   320 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*   330 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*   340 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*   350 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*   360 */    88,   88,   88,   88,   88,   88,   88,   88,   70,   70,
 /*   370 */    70,
};
#define YY_SHIFT_COUNT    (83)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (269)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */   121,  153,   18,   18,   52,  114,  132,    0,  131,   33,
 /*    10 */    33,   33,   33,   33,   33,  162,  139,  244,  245,  244,
 /*    20 */    15,  100,   88,   96,   43,   43,  137,  137,  137,  174,
 /*    30 */     1,    9,   10,   45,   46,   61,   62,   97,   98,  106,
 /*    40 */   107,  142,  133,  152,  154,  170,   35,  176,  178,  182,
 /*    50 */   192,  194,  110,  203,  205,  215,  221,  223,  228,  233,
 /*    60 */   108,   70,  240,  157,  187,  196,  180,  144,  188,   26,
 /*    70 */    67,  190,  243,  175,  227,  212,  253,  229,  251,  252,
 /*    80 */   204,  238,  239,  269,
};
#define YY_REDUCE_COUNT (29)
#define YY_REDUCE_MIN   (-73)
#define YY_REDUCE_MAX   (128)
static const short yy_reduce_ofst[] = {
 /*     0 */   -68,  -61,  -59,  -58,  -73,  -73,  -73,  -60,  -64,  -57,
 /*    10 */   -56,  -51,  -49,  -48,  -47,  -33,  -43,  -34,  -43,    2,
 /*    20 */   -30,   11,   40,   40,   55,   74,   71,   91,  123,  128,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    10 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    20 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    30 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    40 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    50 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    60 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    70 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    80 */   130,  130,  130,  130,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#ifndef NDEBUG
#include <stdio.h>
#include <assert.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "AMP",
  /*    2 */ "AUTHORS",
  /*    3 */ "AVAILABLE",
  /*    4 */ "BANG",
  /*    5 */ "BUG_REPORTS",
  /*    6 */ "BOOL",
  /*    7 */ "BUILD",
  /*    8 */ "BUILD_DOC",
  /*    9 */ "BUILD_ENV",
  /*   10 */ "COLON",
  /*   11 */ "COMMA",
  /*   12 */ "CONFLICTS",
  /*   13 */ "CONFLICT_CLASS",
  /*   14 */ "DEPENDS",
  /*   15 */ "DEPEXTS",
  /*   16 */ "DEPOPTS",
  /*   17 */ "DESCRIPTION",
  /*   18 */ "DEV_REPO",
  /*   19 */ "DOC",
  /*   20 */ "DQ",
  /*   21 */ "EQ",
  /*   22 */ "ERROR",
  /*   23 */ "EXTRA_FILES",
  /*   24 */ "EXTRA_SOURCE",
  /*   25 */ "FALSE",
  /*   26 */ "FEATURES",
  /*   27 */ "FLAGS",
  /*   28 */ "FVF_LOGOP",
  /*   29 */ "HOMEPAGE",
  /*   30 */ "IDENT",
  /*   31 */ "IDENTCHAR",
  /*   32 */ "INSTALL",
  /*   33 */ "INT",
  /*   34 */ "KEYWORD",
  /*   35 */ "LBRACE",
  /*   36 */ "LBRACKET",
  /*   37 */ "LICENSE",
  /*   38 */ "LOGOP",
  /*   39 */ "LPAREN",
  /*   40 */ "MAINTAINER",
  /*   41 */ "MESSAGES",
  /*   42 */ "OPAM_VERSION",
  /*   43 */ "PACKAGE",
  /*   44 */ "PATCHES",
  /*   45 */ "PIN_DEPENDS",
  /*   46 */ "PKGNAME",
  /*   47 */ "POST_MESSAGES",
  /*   48 */ "QMARK",
  /*   49 */ "RBRACE",
  /*   50 */ "RBRACKET",
  /*   51 */ "REMOVE",
  /*   52 */ "RELOP",
  /*   53 */ "RPAREN",
  /*   54 */ "RUNTEST",
  /*   55 */ "SETENV",
  /*   56 */ "SQ",
  /*   57 */ "STRING",
  /*   58 */ "STRING3",
  /*   59 */ "SUBSTS",
  /*   60 */ "SYNOPSIS",
  /*   61 */ "TAGS",
  /*   62 */ "TERM",
  /*   63 */ "TERM_STRING",
  /*   64 */ "TERM_VARIDENT",
  /*   65 */ "TQ",
  /*   66 */ "TRUE",
  /*   67 */ "URL",
  /*   68 */ "VARIDENT",
  /*   69 */ "VERSION",
  /*   70 */ "package",
  /*   71 */ "binding",
  /*   72 */ "fpf",
  /*   73 */ "stringlist",
  /*   74 */ "bindings",
  /*   75 */ "string3",
  /*   76 */ "cmdset",
  /*   77 */ "cmdspec",
  /*   78 */ "cmd",
  /*   79 */ "filter",
  /*   80 */ "args",
  /*   81 */ "arg",
  /*   82 */ "filtered_package_formulas",
  /*   83 */ "fvf_expr",
  /*   84 */ "fvf",
  /*   85 */ "logop_fvf",
  /*   86 */ "fvf_base",
  /*   87 */ "pred",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "package ::= bindings",
 /*   1 */ "bindings ::= binding",
 /*   2 */ "bindings ::= bindings binding",
 /*   3 */ "binding ::= KEYWORD COLON STRING",
 /*   4 */ "binding ::= KEYWORD COLON string3",
 /*   5 */ "binding ::= KEYWORD COLON LBRACKET stringlist RBRACKET",
 /*   6 */ "binding ::= BUILD LBRACKET cmdset RBRACKET",
 /*   7 */ "binding ::= INSTALL LBRACKET cmdset RBRACKET",
 /*   8 */ "binding ::= RUNTEST LBRACKET cmdset RBRACKET",
 /*   9 */ "cmdset ::=",
 /*  10 */ "cmdset ::= cmdset cmdspec",
 /*  11 */ "cmdspec ::= cmd",
 /*  12 */ "cmdspec ::= cmd filter",
 /*  13 */ "cmd ::= LBRACKET args RBRACKET",
 /*  14 */ "args ::=",
 /*  15 */ "args ::= args arg",
 /*  16 */ "arg ::= STRING",
 /*  17 */ "arg ::= VARIDENT",
 /*  18 */ "arg ::= filter",
 /*  19 */ "binding ::= DEPENDS COLON LBRACKET filtered_package_formulas RBRACKET",
 /*  20 */ "binding ::= CONFLICTS COLON LBRACKET filtered_package_formulas RBRACKET",
 /*  21 */ "stringlist ::= STRING",
 /*  22 */ "stringlist ::= stringlist STRING",
 /*  23 */ "filtered_package_formulas ::=",
 /*  24 */ "filtered_package_formulas ::= filtered_package_formulas fpf",
 /*  25 */ "fpf ::= fpf LOGOP fpf",
 /*  26 */ "fpf ::= LPAREN fpf RPAREN",
 /*  27 */ "fpf ::= PKGNAME fvf_expr",
 /*  28 */ "fpf ::= PKGNAME",
 /*  29 */ "fvf_expr ::= LBRACE fvf RBRACE",
 /*  30 */ "fvf ::=",
 /*  31 */ "fvf ::= fvf logop_fvf",
 /*  32 */ "logop_fvf ::= LOGOP fvf",
 /*  33 */ "fvf ::= fvf_base",
 /*  34 */ "fvf_base ::= VERSION",
 /*  35 */ "filter ::= LBRACE pred RBRACE",
 /*  36 */ "pred ::= pred LOGOP pred",
 /*  37 */ "pred ::= INT",
 /*  38 */ "pred ::= STRING",
 /*  39 */ "pred ::= VARIDENT",
 /*  40 */ "pred ::= BANG pred",
 /*  41 */ "pred ::= QMARK pred",
 /*  42 */ "pred ::= LPAREN pred RPAREN",
 /*  43 */ "pred ::= pred RELOP pred",
 /*  44 */ "string3 ::= TQ STRING3 TQ",
 /*  45 */ "string3 ::= TQ STRING3 STRING STRING3 TQ",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    70,  /* (0) package ::= bindings */
    74,  /* (1) bindings ::= binding */
    74,  /* (2) bindings ::= bindings binding */
    71,  /* (3) binding ::= KEYWORD COLON STRING */
    71,  /* (4) binding ::= KEYWORD COLON string3 */
    71,  /* (5) binding ::= KEYWORD COLON LBRACKET stringlist RBRACKET */
    71,  /* (6) binding ::= BUILD LBRACKET cmdset RBRACKET */
    71,  /* (7) binding ::= INSTALL LBRACKET cmdset RBRACKET */
    71,  /* (8) binding ::= RUNTEST LBRACKET cmdset RBRACKET */
    76,  /* (9) cmdset ::= */
    76,  /* (10) cmdset ::= cmdset cmdspec */
    77,  /* (11) cmdspec ::= cmd */
    77,  /* (12) cmdspec ::= cmd filter */
    78,  /* (13) cmd ::= LBRACKET args RBRACKET */
    80,  /* (14) args ::= */
    80,  /* (15) args ::= args arg */
    81,  /* (16) arg ::= STRING */
    81,  /* (17) arg ::= VARIDENT */
    81,  /* (18) arg ::= filter */
    71,  /* (19) binding ::= DEPENDS COLON LBRACKET filtered_package_formulas RBRACKET */
    71,  /* (20) binding ::= CONFLICTS COLON LBRACKET filtered_package_formulas RBRACKET */
    73,  /* (21) stringlist ::= STRING */
    73,  /* (22) stringlist ::= stringlist STRING */
    82,  /* (23) filtered_package_formulas ::= */
    82,  /* (24) filtered_package_formulas ::= filtered_package_formulas fpf */
    72,  /* (25) fpf ::= fpf LOGOP fpf */
    72,  /* (26) fpf ::= LPAREN fpf RPAREN */
    72,  /* (27) fpf ::= PKGNAME fvf_expr */
    72,  /* (28) fpf ::= PKGNAME */
    83,  /* (29) fvf_expr ::= LBRACE fvf RBRACE */
    84,  /* (30) fvf ::= */
    84,  /* (31) fvf ::= fvf logop_fvf */
    85,  /* (32) logop_fvf ::= LOGOP fvf */
    84,  /* (33) fvf ::= fvf_base */
    86,  /* (34) fvf_base ::= VERSION */
    79,  /* (35) filter ::= LBRACE pred RBRACE */
    87,  /* (36) pred ::= pred LOGOP pred */
    87,  /* (37) pred ::= INT */
    87,  /* (38) pred ::= STRING */
    87,  /* (39) pred ::= VARIDENT */
    87,  /* (40) pred ::= BANG pred */
    87,  /* (41) pred ::= QMARK pred */
    87,  /* (42) pred ::= LPAREN pred RPAREN */
    87,  /* (43) pred ::= pred RELOP pred */
    75,  /* (44) string3 ::= TQ STRING3 TQ */
    75,  /* (45) string3 ::= TQ STRING3 STRING STRING3 TQ */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) package ::= bindings */
   -1,  /* (1) bindings ::= binding */
   -2,  /* (2) bindings ::= bindings binding */
   -3,  /* (3) binding ::= KEYWORD COLON STRING */
   -3,  /* (4) binding ::= KEYWORD COLON string3 */
   -5,  /* (5) binding ::= KEYWORD COLON LBRACKET stringlist RBRACKET */
   -4,  /* (6) binding ::= BUILD LBRACKET cmdset RBRACKET */
   -4,  /* (7) binding ::= INSTALL LBRACKET cmdset RBRACKET */
   -4,  /* (8) binding ::= RUNTEST LBRACKET cmdset RBRACKET */
    0,  /* (9) cmdset ::= */
   -2,  /* (10) cmdset ::= cmdset cmdspec */
   -1,  /* (11) cmdspec ::= cmd */
   -2,  /* (12) cmdspec ::= cmd filter */
   -3,  /* (13) cmd ::= LBRACKET args RBRACKET */
    0,  /* (14) args ::= */
   -2,  /* (15) args ::= args arg */
   -1,  /* (16) arg ::= STRING */
   -1,  /* (17) arg ::= VARIDENT */
   -1,  /* (18) arg ::= filter */
   -5,  /* (19) binding ::= DEPENDS COLON LBRACKET filtered_package_formulas RBRACKET */
   -5,  /* (20) binding ::= CONFLICTS COLON LBRACKET filtered_package_formulas RBRACKET */
   -1,  /* (21) stringlist ::= STRING */
   -2,  /* (22) stringlist ::= stringlist STRING */
    0,  /* (23) filtered_package_formulas ::= */
   -2,  /* (24) filtered_package_formulas ::= filtered_package_formulas fpf */
   -3,  /* (25) fpf ::= fpf LOGOP fpf */
   -3,  /* (26) fpf ::= LPAREN fpf RPAREN */
   -2,  /* (27) fpf ::= PKGNAME fvf_expr */
   -1,  /* (28) fpf ::= PKGNAME */
   -3,  /* (29) fvf_expr ::= LBRACE fvf RBRACE */
    0,  /* (30) fvf ::= */
   -2,  /* (31) fvf ::= fvf logop_fvf */
   -2,  /* (32) logop_fvf ::= LOGOP fvf */
   -1,  /* (33) fvf ::= fvf_base */
   -1,  /* (34) fvf_base ::= VERSION */
   -3,  /* (35) filter ::= LBRACE pred RBRACE */
   -3,  /* (36) pred ::= pred LOGOP pred */
   -1,  /* (37) pred ::= INT */
   -1,  /* (38) pred ::= STRING */
   -1,  /* (39) pred ::= VARIDENT */
   -2,  /* (40) pred ::= BANG pred */
   -2,  /* (41) pred ::= QMARK pred */
   -3,  /* (42) pred ::= LPAREN pred RPAREN */
   -3,  /* (43) pred ::= pred RELOP pred */
   -3,  /* (44) string3 ::= TQ STRING3 TQ */
   -5,  /* (45) string3 ::= TQ STRING3 STRING STRING3 TQ */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;
  assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yysize = yyRuleInfoNRhs[yyruleno];
    if( yysize ){
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
        yyTracePrompt,
        yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
        yymsp[yysize].stateno);
    }else{
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
        yyTracePrompt, yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
    }
  }
#endif /* NDEBUG */

  /* Check that the stack is large enough to grow by a single entry
  ** if the RHS of the rule is empty.  This ensures that there is room
  ** enough on the stack to push the LHS value */
  if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
    if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
      yypParser->yyhwm++;
      assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack));
    }
#endif
#if YYSTACKDEPTH>0 
    if( yypParser->yytos>=yypParser->yystackEnd ){
      yyStackOverflow(yypParser);
      /* The call to yyStackOverflow() above pops the stack until it is
      ** empty, causing the main parser loop to exit.  So the return value
      ** is never used and does not matter. */
      return 0;
    }
#else
    if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
      if( yyGrowStack(yypParser) ){
        yyStackOverflow(yypParser);
        /* The call to yyStackOverflow() above pops the stack until it is
        ** empty, causing the main parser loop to exit.  So the return value
        ** is never used and does not matter. */
        return 0;
      }
      yymsp = yypParser->yytos;
    }
#endif
  }

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* package ::= bindings */
#line 164 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "PACKAGE", "");
    LOG_DEBUG(0, " bindings ct: %d",
              HASH_CNT(hh, opam_parse_state->pkg->entries));
}
#line 1253 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 1: /* bindings ::= binding */
#line 170 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "One binding", "");
}
#line 1260 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 2: /* bindings ::= bindings binding */
#line 174 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDINGS ct: %d",
           HASH_CNT(hh, opam_parse_state->pkg->entries));
    /* no need to do anything, opam_parse_state->pkg->entries already
       contains all bindings */
    yylhsminor.yy0 = yymsp[-1].minor.yy0;
}
#line 1271 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 3: /* binding ::= KEYWORD COLON STRING */
      case 4: /* binding ::= KEYWORD COLON string3 */ yytestcase(yyruleno==4);
#line 185 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING: %s: %s", yymsp[-2].minor.yy0.s, yymsp[0].minor.yy0.s);
    /* create a binding and add it to the pkg hashmap */
    yylhsminor.yy33 = calloc(sizeof(struct opam_binding_s), 1);
    yylhsminor.yy33->name = yymsp[-2].minor.yy0.s;
    yylhsminor.yy33->t = BINDING_STRING;
    yylhsminor.yy33->val = strdup(yymsp[0].minor.yy0.s);
    HASH_ADD_KEYPTR(hh, // opam_parse_state->pkg->entries->hh,
                    opam_parse_state->pkg->entries,
                    yylhsminor.yy33->name, strlen(yylhsminor.yy33->name), yylhsminor.yy33);
}
#line 1288 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-2].minor.yy33 = yylhsminor.yy33;
        break;
      case 5: /* binding ::= KEYWORD COLON LBRACKET stringlist RBRACKET */
#line 209 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING stringlist %s, ct: %d",
           yymsp[-4].minor.yy0.s, utarray_len(yymsp[-1].minor.yy126));
    /* create a binding and add it to the pkg hashmap */
    yylhsminor.yy33 = calloc(sizeof(struct opam_binding_s), 1);
    yylhsminor.yy33->name = yymsp[-4].minor.yy0.s;
    yylhsminor.yy33->t = BINDING_STRINGLIST;
    yylhsminor.yy33->val = (void*)yymsp[-1].minor.yy126;
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->entries,
                    yylhsminor.yy33->name, strlen(yylhsminor.yy33->name), yylhsminor.yy33);
#if YYDEBUG
    LOG_DEBUG(0, "BINDING stringlist val ct: %d",
           utarray_len((UT_array*)yylhsminor.yy33->val));
#endif
}
#line 1309 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-4].minor.yy33 = yylhsminor.yy33;
        break;
      case 6: /* binding ::= BUILD LBRACKET cmdset RBRACKET */
#line 231 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING build", "");
    /* opam_parse_state->pkg->entries, */
    yymsp[-3].minor.yy33 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-3].minor.yy33->name = strndup("build", 5);
    yymsp[-3].minor.yy33->t = BINDING_BUILD;
    /* yymsp[-3].minor.yy33->val =  */
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->entries,
                    yymsp[-3].minor.yy33->name, strlen(yymsp[-3].minor.yy33->name), yymsp[-3].minor.yy33);
}
#line 1325 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 7: /* binding ::= INSTALL LBRACKET cmdset RBRACKET */
#line 244 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING install", "");
    yymsp[-3].minor.yy33 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-3].minor.yy33->name = strndup("install", 7);
    yymsp[-3].minor.yy33->t = BINDING_BUILD;
    /* yymsp[-3].minor.yy33->val =  */
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->entries,
                    yymsp[-3].minor.yy33->name, strlen(yymsp[-3].minor.yy33->name), yymsp[-3].minor.yy33);
}
#line 1339 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 8: /* binding ::= RUNTEST LBRACKET cmdset RBRACKET */
#line 256 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING run-test", "");
    yymsp[-3].minor.yy33 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-3].minor.yy33->name = strndup("run-test", 8);
    yymsp[-3].minor.yy33->t = BINDING_BUILD;
    /* yymsp[-3].minor.yy33->val =  */
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->entries,
                    yymsp[-3].minor.yy33->name, strlen(yymsp[-3].minor.yy33->name), yymsp[-3].minor.yy33);
}
#line 1353 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 9: /* cmdset ::= */
#line 267 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "cmdset null", "");
}
#line 1360 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 10: /* cmdset ::= cmdset cmdspec */
#line 271 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "cmdset cmdspec", "");
}
#line 1367 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 11: /* cmdspec ::= cmd */
#line 276 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "cmdspec:: cmd", "");
}
#line 1374 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 12: /* cmdspec ::= cmd filter */
#line 281 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "cmdspec:: cmd filter", "");
}
#line 1381 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 13: /* cmd ::= LBRACKET args RBRACKET */
#line 285 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "cmd:: args", "");
}
#line 1388 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 14: /* args ::= */
#line 289 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "args", "");
}
#line 1395 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 15: /* args ::= args arg */
#line 301 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "args arg: %s", yymsp[0].minor.yy0.s);
}
#line 1402 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 16: /* arg ::= STRING */
#line 309 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "string arg: %s", yymsp[0].minor.yy0.s);
}
#line 1409 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 17: /* arg ::= VARIDENT */
#line 313 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "var arg: %s", yymsp[0].minor.yy0.s);
}
#line 1416 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 18: /* arg ::= filter */
#line 317 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "filter arg", "");
}
#line 1423 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 19: /* binding ::= DEPENDS COLON LBRACKET filtered_package_formulas RBRACKET */
#line 332 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "BINDING depends", "");
#endif
    yymsp[-4].minor.yy33 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-4].minor.yy33->name = strndup("depends", 7);
    yymsp[-4].minor.yy33->t = BINDING_DEPENDS;
    /* yymsp[-4].minor.yy33->val = ... will be list of pkgs */
    /* so here, alloc a UT hash table to hold the list */
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->entries,
                    yymsp[-4].minor.yy33->name,
                    strlen(yymsp[-4].minor.yy33->name),
                    yymsp[-4].minor.yy33);
}
#line 1442 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 20: /* binding ::= CONFLICTS COLON LBRACKET filtered_package_formulas RBRACKET */
#line 349 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "BINDING conflicts", "");
#endif
    yymsp[-4].minor.yy33 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-4].minor.yy33->name = strndup("conflicts", 9);
    yymsp[-4].minor.yy33->t = BINDING_DEPENDS;
    /* yymsp[-4].minor.yy33->val =  */
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->entries,
                    yymsp[-4].minor.yy33->name, strlen(yymsp[-4].minor.yy33->name), yymsp[-4].minor.yy33);
}
#line 1458 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 21: /* stringlist ::= STRING */
#line 362 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
    LOG_DEBUG(0, "STRINGLIST single: %s", yymsp[0].minor.yy0.s);
#endif
    utarray_new(yylhsminor.yy126, &ut_str_icd);
    utarray_push_back(yylhsminor.yy126, &yymsp[0].minor.yy0.s);
}
#line 1469 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[0].minor.yy126 = yylhsminor.yy126;
        break;
      case 22: /* stringlist ::= stringlist STRING */
#line 370 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
    LOG_DEBUG(0, "STRINGLIST multiple, ct: %d; new: %s",
           utarray_len(yymsp[-1].minor.yy126), yymsp[0].minor.yy0.s);
#endif
    utarray_push_back(yymsp[-1].minor.yy126, &yymsp[0].minor.yy0.s);
    yylhsminor.yy126 = yymsp[-1].minor.yy126;
}
#line 1482 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-1].minor.yy126 = yylhsminor.yy126;
        break;
      case 23: /* filtered_package_formulas ::= */
#line 393 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "filtered_package_formulas: null", "");
#endif
    }
#line 1492 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 24: /* filtered_package_formulas ::= filtered_package_formulas fpf */
#line 399 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "filtered_package_formulas leftrec", "");
#endif
    }
#line 1501 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 25: /* fpf ::= fpf LOGOP fpf */
#line 405 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fpf: fpf LOGOP fpf", "");
#endif
    }
#line 1510 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 26: /* fpf ::= LPAREN fpf RPAREN */
#line 411 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fpf: (fpf)", "");
#endif
    }
#line 1519 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 27: /* fpf ::= PKGNAME fvf_expr */
#line 417 "lib/parser/syntaxis/opam_syntaxis.y"
{
        LOG_DEBUG(1, "fpf: pkgname fvf_expr:**************** %s",
                  yymsp[-1].minor.yy0.s);
    }
#line 1527 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 28: /* fpf ::= PKGNAME */
#line 422 "lib/parser/syntaxis/opam_syntaxis.y"
{
        LOG_DEBUG(0, "fpf: **************** pkgname: %s", yymsp[0].minor.yy0.s);
        /* Deps = calloc(sizeof(struct opam_binding_s), 1); */
        /*  */
    }
#line 1536 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 29: /* fvf_expr ::= LBRACE fvf RBRACE */
#line 429 "lib/parser/syntaxis/opam_syntaxis.y"
{
      LOG_DEBUG(0, "fvf_expr: braces", "");
    }
#line 1543 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 30: /* fvf ::= */
#line 445 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fvf: null", "");
#endif
    }
#line 1552 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 31: /* fvf ::= fvf logop_fvf */
#line 451 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fvf: fvf logop_fvf", "");
#endif
    }
#line 1561 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 32: /* logop_fvf ::= LOGOP fvf */
#line 457 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fvf: fvf logop fvf", "");
#endif
    }
#line 1570 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 33: /* fvf ::= fvf_base */
#line 489 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fvf: fvf_base", "");
#endif
       }
#line 1579 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 34: /* fvf_base ::= VERSION */
#line 501 "lib/parser/syntaxis/opam_syntaxis.y"
{ // treated as <string>
#if YYDEBUG
        LOG_DEBUG(0, "fvf_base: version", "");
#endif
    }
#line 1588 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 35: /* filter ::= LBRACE pred RBRACE */
#line 571 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "{pred}", "");
}
#line 1595 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 36: /* pred ::= pred LOGOP pred */
#line 574 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "compound pred: <pred> %s <pred>", yymsp[-1].minor.yy0.s);
}
#line 1602 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 37: /* pred ::= INT */
      case 38: /* pred ::= STRING */ yytestcase(yyruleno==38);
      case 39: /* pred ::= VARIDENT */ yytestcase(yyruleno==39);
#line 577 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "pred: %s", yymsp[0].minor.yy0.s);
}
#line 1611 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 40: /* pred ::= BANG pred */
#line 586 "lib/parser/syntaxis/opam_syntaxis.y"
{
        LOG_DEBUG(0, "pred: BANG filter", "");
}
#line 1618 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 41: /* pred ::= QMARK pred */
#line 589 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "pred: QMARK pred", "");
}
#line 1625 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 42: /* pred ::= LPAREN pred RPAREN */
#line 592 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "pred: (pred)", "");
}
#line 1632 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 43: /* pred ::= pred RELOP pred */
#line 595 "lib/parser/syntaxis/opam_syntaxis.y"
{
        LOG_DEBUG(0, "pred: pred %s pred", yymsp[-1].minor.yy0.s);
}
#line 1639 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 44: /* string3 ::= TQ STRING3 TQ */
      case 45: /* string3 ::= TQ STRING3 STRING STRING3 TQ */ yytestcase(yyruleno==45);
#line 641 "lib/parser/syntaxis/opam_syntaxis.y"
{
}
#line 1646 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 156 "lib/parser/syntaxis/opam_syntaxis.y"

    LOG_ERROR(0, "Giving up.  Parser is hopelessly lost... %d",
    yypParser->yyerrcnt);
#line 1694 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 133 "lib/parser/syntaxis/opam_syntaxis.y"

    LOG_ERROR(0, RED "SYNTAX ERROR" CRESET " yymajor: %d", yymajor);
    LOG_ERROR(0, RED "tos.stateno" CRESET ": %d", yypParser->yytos->stateno);
    LOG_ERROR(0, RED "tos.major" CRESET ": %d", yypParser->yytos->major);
    LOG_ERROR(0, RED "tos.minor" CRESET ": %d", yypParser->yytos->minor);
/* args passed:
   yyParser *yypParser, /\* The parser *\/
   int yymajor, /\* The major type of the error token *\/
   ParseTOKENTYPE yyminor /\* The minor type of the error token *\/
   ParseTOKENTYPE is union opam_token_u
 */

                            
                      
     
     log_error("trying to recover...");
      
#line 1731 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
#line 152 "lib/parser/syntaxis/opam_syntaxis.y"

    LOG_TRACE(0, "Parsing complete", "");
#line 1760 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  do{
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      yyact = yy_reduce(yypParser,yyact-YY_MIN_REDUCE,yymajor,
                        yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos >= yypParser->yystack
            && (yyact = yy_find_reduce_action(
                        yypParser->yytos->stateno,
                        YYERRORSYMBOL)) > YY_MAX_SHIFTREDUCE
        ){
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos < yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }while( yypParser->yytos>yypParser->yystack );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
